apiVersion: v1
kind: Secret
metadata:
  name: token-secret
  namespace: visionone-filesecurity
type: Opaque
stringData:
  registration-token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJjaWQiOiI3ZGRjNDIwOC00YjgxLTQ1YmQtOWM3Mi02ZGNmZTAxNDdiYjYiLCJjcGlkIjoic3ZwIiwicHBpZCI6InNmcyIsIml0IjoxNzc0Mzc2NzM1LCJ1aWQiOiIiLCJwbCI6IntcImRvbWFpblwiOiBcImFwaS5ldS54ZHIudHJlbmRtaWNyby5jb21cIn0iLCJldCI6MTc3NDk4MTUzNSwiZGlkIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAwIiwidG9rZW5Vc2UiOiJkZXZpY2UifQ.RPkooVl-WACJNiXd2R5Z6fioMzRLrNg45FniZwc5cqSv4rq8vp5L1OCHffEw-STzDLAYwOuRYttfSRJkCRiDihkQRdCHpl07tALFRKzce6ukXsmAmoHdzJ0f0jTFg_2mUmXxugmwNJylj47k7ayV0tt9mwNoObhmeOBgNbK5NkX5eF2pjpmwjkexRfjgTVHHYiXx2BmGO4oGoDiv-Ahe8ixDNfd2cxzG21CGqUBioXUWxudtlgm8mSnz7hynjxWORzHoPn5qK8nTS07I8hBSn3osk5-cKjI_mYm_-IkPo4Zdo7-7FDx0NfePqBEMFrQgneXwtJjkoEEkBNqPjXe7sF4CBIbG_NCXUI-NZRuqbMWJWr58y02ql0SWIet8tr14yFobmzVaaHy9f8YcCFzKtDfWvQX_wF9TjJv7hB52hGgXFoCEw3izGCoxrx3gZKmB80dWPABfLTM0mQ8K5F5y2oHplVUSSV582U4jFRNdZzGr5kALYoT56tqfD3klWc3y9mwYIPIvPSYA0fUbIneSS7GqfiIPWSFMP02UnTEojwHl8BlC6TbymX4bgzD213PxeKTxLaUpT1ygZA-_Qd07GD2sbM6ZiUV3NWKV8vOWTQ1xlYARkQAbGzHpYbo2VgTBr088l2j_8vEUERd9RW5wcHvdKleZREcz5S00Z_3LNYw"

---
apiVersion: v1
kind: Secret
metadata:
  name: device-token-secret
  namespace: visionone-filesecurity
type: Opaque
stringData: {}